/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AccountIds
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class AccountIds {

    public static final String SERIALIZED_NAME_PUBLIC_KEYS = "publicKeys";
    public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
    @SerializedName(SERIALIZED_NAME_PUBLIC_KEYS)
    private List<String> publicKeys = new ArrayList<String>();
    @SerializedName(SERIALIZED_NAME_ADDRESSES)
    private List<String> addresses = new ArrayList<String>();

    public AccountIds publicKeys(List<String> publicKeys) {
        this.publicKeys = publicKeys;
        return this;
    }

    public AccountIds addPublicKeysItem(String publicKeysItem) {
        if (this.publicKeys == null) {
            this.publicKeys = new ArrayList<String>();
        }
        this.publicKeys.add(publicKeysItem);
        return this;
    }

    /**
     * The array of public keys.
     *
     * @return publicKeys
     */
    @ApiModelProperty(
        example = "[AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26]",
        value = "The array of public keys.")
    public List<String> getPublicKeys() {
        return publicKeys;
    }

    public void setPublicKeys(List<String> publicKeys) {
        this.publicKeys = publicKeys;
    }

    public AccountIds addresses(List<String> addresses) {
        this.addresses = addresses;
        return this;
    }

    public AccountIds addAddressesItem(String addressesItem) {
        if (this.addresses == null) {
            this.addresses = new ArrayList<String>();
        }
        this.addresses.add(addressesItem);
        return this;
    }

    /**
     * The array of addresses.
     *
     * @return addresses
     */
    @ApiModelProperty(
        example =
            "[SDRDGFTDLLCB67D4HPGIMIHPNSRYRJRT7DOBGWZY, SBCPGZ3S2SCC3YHBBTYDCUZV4ZZEPHM2KGCP4QXX]",
        value = "The array of addresses.")
    public List<String> getAddresses() {
        return addresses;
    }

    public void setAddresses(List<String> addresses) {
        this.addresses = addresses;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountIds accountIds = (AccountIds) o;
        return Objects.equals(this.publicKeys, accountIds.publicKeys)
            && Objects.equals(this.addresses, accountIds.addresses);
    }

    @Override
    public int hashCode() {
        return Objects.hash(publicKeys, addresses);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountIds {\n");
        sb.append("    publicKeys: ").append(toIndentedString(publicKeys)).append("\n");
        sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
