/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AccountNamesDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class AccountNamesDTO {

    public static final String SERIALIZED_NAME_ADDRESS = "address";
    public static final String SERIALIZED_NAME_NAMES = "names";
    @SerializedName(SERIALIZED_NAME_ADDRESS)
    private String address;
    @SerializedName(SERIALIZED_NAME_NAMES)
    private List<String> names = new ArrayList<String>();

    public AccountNamesDTO address(String address) {
        this.address = address;
        return this;
    }

    /**
     * The address of the account in base 32.
     *
     * @return address
     */
    @ApiModelProperty(
        example = "SAAM2O7SSJ2A7AU3DZJMSTTRFZT5TFDPQ3ZIIJX7",
        required = true,
        value = "The address of the account in base 32.")
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public AccountNamesDTO names(List<String> names) {
        this.names = names;
        return this;
    }

    public AccountNamesDTO addNamesItem(String namesItem) {
        this.names.add(namesItem);
        return this;
    }

    /**
     * The mosaic linked namespace names.
     *
     * @return names
     */
    @ApiModelProperty(
        example = "[alias1, alias2]",
        required = true,
        value = "The mosaic linked namespace names.")
    public List<String> getNames() {
        return names;
    }

    public void setNames(List<String> names) {
        this.names = names;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountNamesDTO accountNamesDTO = (AccountNamesDTO) o;
        return Objects.equals(this.address, accountNamesDTO.address)
            && Objects.equals(this.names, accountNamesDTO.names);
    }

    @Override
    public int hashCode() {
        return Objects.hash(address, names);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountNamesDTO {\n");
        sb.append("    address: ").append(toIndentedString(address)).append("\n");
        sb.append("    names: ").append(toIndentedString(names)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
