/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * The alias type: * 0 - No alias. * 1 - Mosaic id alias. * 2 - Addres alias.
 */
@JsonAdapter(AliasTypeEnum.Adapter.class)
public enum AliasTypeEnum {
    NUMBER_0(0),

    NUMBER_1(1),

    NUMBER_2(2);

    private Integer value;

    AliasTypeEnum(Integer value) {
        this.value = value;
    }

    public static AliasTypeEnum fromValue(Integer value) {
        for (AliasTypeEnum b : AliasTypeEnum.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public Integer getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static class Adapter extends TypeAdapter<AliasTypeEnum> {

        @Override
        public void write(final JsonWriter jsonWriter, final AliasTypeEnum enumeration)
            throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public AliasTypeEnum read(final JsonReader jsonReader) throws IOException {
            Integer value = jsonReader.nextInt();
            return AliasTypeEnum.fromValue(value);
        }
    }
}
