/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BlockchainScoreDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class BlockchainScoreDTO {

    public static final String SERIALIZED_NAME_SCORE_HIGH = "scoreHigh";
    public static final String SERIALIZED_NAME_SCORE_LOW = "scoreLow";
    @SerializedName(SERIALIZED_NAME_SCORE_HIGH)
    private List<Integer> scoreHigh = new ArrayList<Integer>();
    @SerializedName(SERIALIZED_NAME_SCORE_LOW)
    private List<Integer> scoreLow = new ArrayList<Integer>();

    public BlockchainScoreDTO scoreHigh(List<Integer> scoreHigh) {
        this.scoreHigh = scoreHigh;
        return this;
    }

    public BlockchainScoreDTO addScoreHighItem(Integer scoreHighItem) {
        this.scoreHigh.add(scoreHighItem);
        return this;
    }

    /**
     * Get scoreHigh
     *
     * @return scoreHigh
     */
    @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
    public List<Integer> getScoreHigh() {
        return scoreHigh;
    }

    public void setScoreHigh(List<Integer> scoreHigh) {
        this.scoreHigh = scoreHigh;
    }

    public BlockchainScoreDTO scoreLow(List<Integer> scoreLow) {
        this.scoreLow = scoreLow;
        return this;
    }

    public BlockchainScoreDTO addScoreLowItem(Integer scoreLowItem) {
        this.scoreLow.add(scoreLowItem);
        return this;
    }

    /**
     * Get scoreLow
     *
     * @return scoreLow
     */
    @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
    public List<Integer> getScoreLow() {
        return scoreLow;
    }

    public void setScoreLow(List<Integer> scoreLow) {
        this.scoreLow = scoreLow;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BlockchainScoreDTO blockchainScoreDTO = (BlockchainScoreDTO) o;
        return Objects.equals(this.scoreHigh, blockchainScoreDTO.scoreHigh)
            && Objects.equals(this.scoreLow, blockchainScoreDTO.scoreLow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(scoreHigh, scoreLow);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BlockchainScoreDTO {\n");
        sb.append("    scoreHigh: ").append(toIndentedString(scoreHigh)).append("\n");
        sb.append("    scoreLow: ").append(toIndentedString(scoreLow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
