/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nem.sdk.infrastructure.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CommunicationTimestamps
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class CommunicationTimestamps {
  public static final String SERIALIZED_NAME_SEND_TIMESTAMP = "sendTimestamp";
  @SerializedName(SERIALIZED_NAME_SEND_TIMESTAMP)
  private List<Integer> sendTimestamp = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_RECEIVE_TIMESTAMP = "receiveTimestamp";
  @SerializedName(SERIALIZED_NAME_RECEIVE_TIMESTAMP)
  private List<Integer> receiveTimestamp = new ArrayList<Integer>();

  public CommunicationTimestamps sendTimestamp(List<Integer> sendTimestamp) {
    this.sendTimestamp = sendTimestamp;
    return this;
  }

  public CommunicationTimestamps addSendTimestampItem(Integer sendTimestampItem) {
    if (this.sendTimestamp == null) {
      this.sendTimestamp = new ArrayList<Integer>();
    }
    this.sendTimestamp.add(sendTimestampItem);
    return this;
  }

   /**
   * Get sendTimestamp
   * @return sendTimestamp
  **/
  @ApiModelProperty(example = "[lower, higher]", value = "")
  public List<Integer> getSendTimestamp() {
    return sendTimestamp;
  }

  public void setSendTimestamp(List<Integer> sendTimestamp) {
    this.sendTimestamp = sendTimestamp;
  }

  public CommunicationTimestamps receiveTimestamp(List<Integer> receiveTimestamp) {
    this.receiveTimestamp = receiveTimestamp;
    return this;
  }

  public CommunicationTimestamps addReceiveTimestampItem(Integer receiveTimestampItem) {
    if (this.receiveTimestamp == null) {
      this.receiveTimestamp = new ArrayList<Integer>();
    }
    this.receiveTimestamp.add(receiveTimestampItem);
    return this;
  }

   /**
   * Get receiveTimestamp
   * @return receiveTimestamp
  **/
  @ApiModelProperty(example = "[lower, higher]", value = "")
  public List<Integer> getReceiveTimestamp() {
    return receiveTimestamp;
  }

  public void setReceiveTimestamp(List<Integer> receiveTimestamp) {
    this.receiveTimestamp = receiveTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationTimestamps communicationTimestamps = (CommunicationTimestamps) o;
    return Objects.equals(this.sendTimestamp, communicationTimestamps.sendTimestamp) &&
        Objects.equals(this.receiveTimestamp, communicationTimestamps.receiveTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendTimestamp, receiveTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationTimestamps {\n");
    sb.append("    sendTimestamp: ").append(toIndentedString(sendTimestamp)).append("\n");
    sb.append("    receiveTimestamp: ").append(toIndentedString(receiveTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

