/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Cosignature
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class Cosignature {

    public static final String SERIALIZED_NAME_PARENT_HASH = "parentHash";
    public static final String SERIALIZED_NAME_SIGNATURE = "signature";
    public static final String SERIALIZED_NAME_SIGNER = "signer";
    @SerializedName(SERIALIZED_NAME_PARENT_HASH)
    private String parentHash;
    @SerializedName(SERIALIZED_NAME_SIGNATURE)
    private String signature;
    @SerializedName(SERIALIZED_NAME_SIGNER)
    private String signer;

    public Cosignature parentHash(String parentHash) {
        this.parentHash = parentHash;
        return this;
    }

    /**
     * The hash of parent aggregate transaction that has been signed by a cosignatory of the
     * transaction.
     *
     * @return parentHash
     */
    @ApiModelProperty(
        value =
            "The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.")
    public String getParentHash() {
        return parentHash;
    }

    public void setParentHash(String parentHash) {
        this.parentHash = parentHash;
    }

    public Cosignature signature(String signature) {
        this.signature = signature;
        return this;
    }

    /**
     * The signatures generated by signing the parent aggregate transaction hash.
     *
     * @return signature
     */
    @ApiModelProperty(
        value = "The signatures generated by signing the parent aggregate transaction hash.")
    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public Cosignature signer(String signer) {
        this.signer = signer;
        return this;
    }

    /**
     * The signer of the transaction.
     *
     * @return signer
     */
    @ApiModelProperty(value = "The signer of the transaction.")
    public String getSigner() {
        return signer;
    }

    public void setSigner(String signer) {
        this.signer = signer;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Cosignature cosignature = (Cosignature) o;
        return Objects.equals(this.parentHash, cosignature.parentHash)
            && Objects.equals(this.signature, cosignature.signature)
            && Objects.equals(this.signer, cosignature.signer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(parentHash, signature, signer);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Cosignature {\n");
        sb.append("    parentHash: ").append(toIndentedString(parentHash)).append("\n");
        sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
        sb.append("    signer: ").append(toIndentedString(signer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
