/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MosaicDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class MosaicDTO {

    public static final String SERIALIZED_NAME_ID = "id";
    public static final String SERIALIZED_NAME_AMOUNT = "amount";
    @SerializedName(SERIALIZED_NAME_ID)
    private List<Integer> id = new ArrayList<Integer>();
    @SerializedName(SERIALIZED_NAME_AMOUNT)
    private List<Integer> amount = new ArrayList<Integer>();

    public MosaicDTO id(List<Integer> id) {
        this.id = id;
        return this;
    }

    public MosaicDTO addIdItem(Integer idItem) {
        this.id.add(idItem);
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
    public List<Integer> getId() {
        return id;
    }

    public void setId(List<Integer> id) {
        this.id = id;
    }

    public MosaicDTO amount(List<Integer> amount) {
        this.amount = amount;
        return this;
    }

    public MosaicDTO addAmountItem(Integer amountItem) {
        this.amount.add(amountItem);
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     */
    @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
    public List<Integer> getAmount() {
        return amount;
    }

    public void setAmount(List<Integer> amount) {
        this.amount = amount;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MosaicDTO mosaicDTO = (MosaicDTO) o;
        return Objects.equals(this.id, mosaicDTO.id) && Objects
            .equals(this.amount, mosaicDTO.amount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, amount);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MosaicDTO {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
