/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MultisigDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class MultisigDTO {

    public static final String SERIALIZED_NAME_ACCOUNT = "account";
    public static final String SERIALIZED_NAME_ACCOUNT_ADDRESS = "accountAddress";
    public static final String SERIALIZED_NAME_MIN_APPROVAL = "minApproval";
    public static final String SERIALIZED_NAME_MIN_REMOVAL = "minRemoval";
    public static final String SERIALIZED_NAME_COSIGNATORIES = "cosignatories";
    public static final String SERIALIZED_NAME_MULTISIG_ACCOUNTS = "multisigAccounts";
    @SerializedName(SERIALIZED_NAME_ACCOUNT)
    private String account;
    @SerializedName(SERIALIZED_NAME_ACCOUNT_ADDRESS)
    private String accountAddress;
    @SerializedName(SERIALIZED_NAME_MIN_APPROVAL)
    private Integer minApproval;
    @SerializedName(SERIALIZED_NAME_MIN_REMOVAL)
    private Integer minRemoval;
    @SerializedName(SERIALIZED_NAME_COSIGNATORIES)
    private List<String> cosignatories = new ArrayList<String>();
    @SerializedName(SERIALIZED_NAME_MULTISIG_ACCOUNTS)
    private List<String> multisigAccounts = new ArrayList<String>();

    public MultisigDTO account(String account) {
        this.account = account;
        return this;
    }

    /**
     * The account public key.
     *
     * @return account
     */
    @ApiModelProperty(
        example = "AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26",
        required = true,
        value = "The account public key.")
    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public MultisigDTO accountAddress(String accountAddress) {
        this.accountAddress = accountAddress;
        return this;
    }

    /**
     * The account address in hexadecimal.
     *
     * @return accountAddress
     */
    @ApiModelProperty(
        example = "9081FCCB41F8C8409A9B99E485E0E28D23BD6304EF7215E01A",
        value = "The account address in hexadecimal.")
    public String getAccountAddress() {
        return accountAddress;
    }

    public void setAccountAddress(String accountAddress) {
        this.accountAddress = accountAddress;
    }

    public MultisigDTO minApproval(Integer minApproval) {
        this.minApproval = minApproval;
        return this;
    }

    /**
     * The number of signatures needed to approve a transaction.
     *
     * @return minApproval
     */
    @ApiModelProperty(
        example = "2",
        required = true,
        value = "The number of signatures needed to approve a transaction.")
    public Integer getMinApproval() {
        return minApproval;
    }

    public void setMinApproval(Integer minApproval) {
        this.minApproval = minApproval;
    }

    public MultisigDTO minRemoval(Integer minRemoval) {
        this.minRemoval = minRemoval;
        return this;
    }

    /**
     * The number of signatures needed to remove a cosignatory.
     *
     * @return minRemoval
     */
    @ApiModelProperty(
        example = "1",
        required = true,
        value = "The number of signatures needed to remove a cosignatory.")
    public Integer getMinRemoval() {
        return minRemoval;
    }

    public void setMinRemoval(Integer minRemoval) {
        this.minRemoval = minRemoval;
    }

    public MultisigDTO cosignatories(List<String> cosignatories) {
        this.cosignatories = cosignatories;
        return this;
    }

    public MultisigDTO addCosignatoriesItem(String cosignatoriesItem) {
        this.cosignatories.add(cosignatoriesItem);
        return this;
    }

    /**
     * The array of public keys of the cosignatory accounts.
     *
     * @return cosignatories
     */
    @ApiModelProperty(
        example =
            "[5D9513282B65A12A1B68DCB67DB64245721F7AE7822BE441FE813173803C512C, AC1A6E1D8DE5B17D2C6B1293F1CAD3829EEACF38D09311BB3C8E5A880092DE26]",
        required = true,
        value = "The array of public keys of the cosignatory accounts.")
    public List<String> getCosignatories() {
        return cosignatories;
    }

    public void setCosignatories(List<String> cosignatories) {
        this.cosignatories = cosignatories;
    }

    public MultisigDTO multisigAccounts(List<String> multisigAccounts) {
        this.multisigAccounts = multisigAccounts;
        return this;
    }

    public MultisigDTO addMultisigAccountsItem(String multisigAccountsItem) {
        this.multisigAccounts.add(multisigAccountsItem);
        return this;
    }

    /**
     * The array of multisig accounts where the account is cosignatory.
     *
     * @return multisigAccounts
     */
    @ApiModelProperty(
        example = "[565059F55E68F904214E8BE1D610B5BBEA4CE46CC13D246D45BC1DAE5D32A0D2]",
        required = true,
        value = "The array of multisig accounts where the account is cosignatory.")
    public List<String> getMultisigAccounts() {
        return multisigAccounts;
    }

    public void setMultisigAccounts(List<String> multisigAccounts) {
        this.multisigAccounts = multisigAccounts;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MultisigDTO multisigDTO = (MultisigDTO) o;
        return Objects.equals(this.account, multisigDTO.account)
            && Objects.equals(this.accountAddress, multisigDTO.accountAddress)
            && Objects.equals(this.minApproval, multisigDTO.minApproval)
            && Objects.equals(this.minRemoval, multisigDTO.minRemoval)
            && Objects.equals(this.cosignatories, multisigDTO.cosignatories)
            && Objects.equals(this.multisigAccounts, multisigDTO.multisigAccounts);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            account, accountAddress, minApproval, minRemoval, cosignatories, multisigAccounts);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MultisigDTO {\n");
        sb.append("    account: ").append(toIndentedString(account)).append("\n");
        sb.append("    accountAddress: ").append(toIndentedString(accountAddress)).append("\n");
        sb.append("    minApproval: ").append(toIndentedString(minApproval)).append("\n");
        sb.append("    minRemoval: ").append(toIndentedString(minRemoval)).append("\n");
        sb.append("    cosignatories: ").append(toIndentedString(cosignatories)).append("\n");
        sb.append("    multisigAccounts: ").append(toIndentedString(multisigAccounts)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
