/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MultisigAccountGraphInfoDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class MultisigAccountGraphInfoDTO {

    public static final String SERIALIZED_NAME_LEVEL = "level";
    public static final String SERIALIZED_NAME_MULTISIG_ENTRIES = "multisigEntries";
    @SerializedName(SERIALIZED_NAME_LEVEL)
    private Integer level;
    @SerializedName(SERIALIZED_NAME_MULTISIG_ENTRIES)
    private List<MultisigAccountInfoDTO> multisigEntries = new ArrayList<MultisigAccountInfoDTO>();

    public MultisigAccountGraphInfoDTO level(Integer level) {
        this.level = level;
        return this;
    }

    /**
     * The level of the multisig account.
     *
     * @return level
     */
    @ApiModelProperty(example = "0", required = true, value = "The level of the multisig account.")
    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public MultisigAccountGraphInfoDTO multisigEntries(
        List<MultisigAccountInfoDTO> multisigEntries) {
        this.multisigEntries = multisigEntries;
        return this;
    }

    public MultisigAccountGraphInfoDTO addMultisigEntriesItem(
        MultisigAccountInfoDTO multisigEntriesItem) {
        this.multisigEntries.add(multisigEntriesItem);
        return this;
    }

    /**
     * The array of multisig accounts for this level.
     *
     * @return multisigEntries
     */
    @ApiModelProperty(required = true, value = "The array of multisig accounts for this level.")
    public List<MultisigAccountInfoDTO> getMultisigEntries() {
        return multisigEntries;
    }

    public void setMultisigEntries(List<MultisigAccountInfoDTO> multisigEntries) {
        this.multisigEntries = multisigEntries;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MultisigAccountGraphInfoDTO multisigAccountGraphInfoDTO = (MultisigAccountGraphInfoDTO) o;
        return Objects.equals(this.level, multisigAccountGraphInfoDTO.level)
            && Objects.equals(this.multisigEntries, multisigAccountGraphInfoDTO.multisigEntries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(level, multisigEntries);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MultisigAccountGraphInfoDTO {\n");
        sb.append("    level: ").append(toIndentedString(level)).append("\n");
        sb.append("    multisigEntries: ").append(toIndentedString(multisigEntries)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
