/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nem.sdk.infrastructure.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import io.nem.sdk.infrastructure.model.AliasDTO;
import io.nem.sdk.infrastructure.model.NamespaceTypeEnum;

/**
 * NamespaceDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class NamespaceDTO {
  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private String owner;

  public static final String SERIALIZED_NAME_OWNER_ADDRESS = "ownerAddress";
  @SerializedName(SERIALIZED_NAME_OWNER_ADDRESS)
  private String ownerAddress;

  public static final String SERIALIZED_NAME_START_HEIGHT = "startHeight";
  @SerializedName(SERIALIZED_NAME_START_HEIGHT)
  private List<Integer> startHeight = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_END_HEIGHT = "endHeight";
  @SerializedName(SERIALIZED_NAME_END_HEIGHT)
  private List<Integer> endHeight = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_DEPTH = "depth";
  @SerializedName(SERIALIZED_NAME_DEPTH)
  private Integer depth;

  public static final String SERIALIZED_NAME_LEVEL0 = "level0";
  @SerializedName(SERIALIZED_NAME_LEVEL0)
  private List<Integer> level0 = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_LEVEL1 = "level1";
  @SerializedName(SERIALIZED_NAME_LEVEL1)
  private List<Integer> level1 = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_LEVEL2 = "level2";
  @SerializedName(SERIALIZED_NAME_LEVEL2)
  private List<Integer> level2 = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private NamespaceTypeEnum type;

  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  private AliasDTO alias = null;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private List<Integer> parentId = new ArrayList<Integer>();

  public NamespaceDTO owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * The public key of the owner of the namespace.
   * @return owner
  **/
  @ApiModelProperty(example = "EFF9BC7472263D03EF6362B1F200FD3061BCD1BABE78F82119FB88811227CE85", required = true, value = "The public key of the owner of the namespace.")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public NamespaceDTO ownerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
    return this;
  }

   /**
   * The address of the owner of the namespace in hexadecimal.
   * @return ownerAddress
  **/
  @ApiModelProperty(example = "906CBD9B8EC88014F7A4181B00C1837646BD46E504E3D72C44", required = true, value = "The address of the owner of the namespace in hexadecimal.")
  public String getOwnerAddress() {
    return ownerAddress;
  }

  public void setOwnerAddress(String ownerAddress) {
    this.ownerAddress = ownerAddress;
  }

  public NamespaceDTO startHeight(List<Integer> startHeight) {
    this.startHeight = startHeight;
    return this;
  }

  public NamespaceDTO addStartHeightItem(Integer startHeightItem) {
    this.startHeight.add(startHeightItem);
    return this;
  }

   /**
   * Get startHeight
   * @return startHeight
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getStartHeight() {
    return startHeight;
  }

  public void setStartHeight(List<Integer> startHeight) {
    this.startHeight = startHeight;
  }

  public NamespaceDTO endHeight(List<Integer> endHeight) {
    this.endHeight = endHeight;
    return this;
  }

  public NamespaceDTO addEndHeightItem(Integer endHeightItem) {
    this.endHeight.add(endHeightItem);
    return this;
  }

   /**
   * Get endHeight
   * @return endHeight
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getEndHeight() {
    return endHeight;
  }

  public void setEndHeight(List<Integer> endHeight) {
    this.endHeight = endHeight;
  }

  public NamespaceDTO depth(Integer depth) {
    this.depth = depth;
    return this;
  }

   /**
   * The level of the namespace.
   * @return depth
  **/
  @ApiModelProperty(example = "1", required = true, value = "The level of the namespace.")
  public Integer getDepth() {
    return depth;
  }

  public void setDepth(Integer depth) {
    this.depth = depth;
  }

  public NamespaceDTO level0(List<Integer> level0) {
    this.level0 = level0;
    return this;
  }

  public NamespaceDTO addLevel0Item(Integer level0Item) {
    this.level0.add(level0Item);
    return this;
  }

   /**
   * Get level0
   * @return level0
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getLevel0() {
    return level0;
  }

  public void setLevel0(List<Integer> level0) {
    this.level0 = level0;
  }

  public NamespaceDTO level1(List<Integer> level1) {
    this.level1 = level1;
    return this;
  }

  public NamespaceDTO addLevel1Item(Integer level1Item) {
    if (this.level1 == null) {
      this.level1 = new ArrayList<Integer>();
    }
    this.level1.add(level1Item);
    return this;
  }

   /**
   * Get level1
   * @return level1
  **/
  @ApiModelProperty(example = "[lower, higher]", value = "")
  public List<Integer> getLevel1() {
    return level1;
  }

  public void setLevel1(List<Integer> level1) {
    this.level1 = level1;
  }

  public NamespaceDTO level2(List<Integer> level2) {
    this.level2 = level2;
    return this;
  }

  public NamespaceDTO addLevel2Item(Integer level2Item) {
    if (this.level2 == null) {
      this.level2 = new ArrayList<Integer>();
    }
    this.level2.add(level2Item);
    return this;
  }

   /**
   * Get level2
   * @return level2
  **/
  @ApiModelProperty(example = "[lower, higher]", value = "")
  public List<Integer> getLevel2() {
    return level2;
  }

  public void setLevel2(List<Integer> level2) {
    this.level2 = level2;
  }

  public NamespaceDTO type(NamespaceTypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public NamespaceTypeEnum getType() {
    return type;
  }

  public void setType(NamespaceTypeEnum type) {
    this.type = type;
  }

  public NamespaceDTO alias(AliasDTO alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(required = true, value = "")
  public AliasDTO getAlias() {
    return alias;
  }

  public void setAlias(AliasDTO alias) {
    this.alias = alias;
  }

  public NamespaceDTO parentId(List<Integer> parentId) {
    this.parentId = parentId;
    return this;
  }

  public NamespaceDTO addParentIdItem(Integer parentIdItem) {
    this.parentId.add(parentIdItem);
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getParentId() {
    return parentId;
  }

  public void setParentId(List<Integer> parentId) {
    this.parentId = parentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NamespaceDTO namespaceDTO = (NamespaceDTO) o;
    return Objects.equals(this.owner, namespaceDTO.owner) &&
        Objects.equals(this.ownerAddress, namespaceDTO.ownerAddress) &&
        Objects.equals(this.startHeight, namespaceDTO.startHeight) &&
        Objects.equals(this.endHeight, namespaceDTO.endHeight) &&
        Objects.equals(this.depth, namespaceDTO.depth) &&
        Objects.equals(this.level0, namespaceDTO.level0) &&
        Objects.equals(this.level1, namespaceDTO.level1) &&
        Objects.equals(this.level2, namespaceDTO.level2) &&
        Objects.equals(this.type, namespaceDTO.type) &&
        Objects.equals(this.alias, namespaceDTO.alias) &&
        Objects.equals(this.parentId, namespaceDTO.parentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, ownerAddress, startHeight, endHeight, depth, level0, level1, level2, type, alias, parentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NamespaceDTO {\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerAddress: ").append(toIndentedString(ownerAddress)).append("\n");
    sb.append("    startHeight: ").append(toIndentedString(startHeight)).append("\n");
    sb.append("    endHeight: ").append(toIndentedString(endHeight)).append("\n");
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("    level0: ").append(toIndentedString(level0)).append("\n");
    sb.append("    level1: ").append(toIndentedString(level1)).append("\n");
    sb.append("    level2: ").append(toIndentedString(level2)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

