/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nem.sdk.infrastructure.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import io.nem.sdk.infrastructure.model.ResolutionEntryDTO;

/**
 * A resolution statement keeps the relation between a namespace alias used in a transaction and the real address or mosaicId.
 */
@ApiModel(description = "A resolution statement keeps the relation between a namespace alias used in a transaction and the real address or mosaicId.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class ResolutionStatementDTO {
  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private List<Integer> height = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_UNRESOLVED = "unresolved";
  @SerializedName(SERIALIZED_NAME_UNRESOLVED)
  private List<Integer> unresolved = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_RESOLUTION_ENTRIES = "resolutionEntries";
  @SerializedName(SERIALIZED_NAME_RESOLUTION_ENTRIES)
  private List<ResolutionEntryDTO> resolutionEntries = new ArrayList<ResolutionEntryDTO>();

  public ResolutionStatementDTO height(List<Integer> height) {
    this.height = height;
    return this;
  }

  public ResolutionStatementDTO addHeightItem(Integer heightItem) {
    this.height.add(heightItem);
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getHeight() {
    return height;
  }

  public void setHeight(List<Integer> height) {
    this.height = height;
  }

  public ResolutionStatementDTO unresolved(List<Integer> unresolved) {
    this.unresolved = unresolved;
    return this;
  }

  public ResolutionStatementDTO addUnresolvedItem(Integer unresolvedItem) {
    this.unresolved.add(unresolvedItem);
    return this;
  }

   /**
   * Get unresolved
   * @return unresolved
  **/
  @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
  public List<Integer> getUnresolved() {
    return unresolved;
  }

  public void setUnresolved(List<Integer> unresolved) {
    this.unresolved = unresolved;
  }

  public ResolutionStatementDTO resolutionEntries(List<ResolutionEntryDTO> resolutionEntries) {
    this.resolutionEntries = resolutionEntries;
    return this;
  }

  public ResolutionStatementDTO addResolutionEntriesItem(ResolutionEntryDTO resolutionEntriesItem) {
    this.resolutionEntries.add(resolutionEntriesItem);
    return this;
  }

   /**
   * The array of resolution entries linked to the unresolved namespaceId. It is an array instead of a single UInt64 field since within one block the resolution might change for different sources due to alias related transactions.
   * @return resolutionEntries
  **/
  @ApiModelProperty(required = true, value = "The array of resolution entries linked to the unresolved namespaceId. It is an array instead of a single UInt64 field since within one block the resolution might change for different sources due to alias related transactions.")
  public List<ResolutionEntryDTO> getResolutionEntries() {
    return resolutionEntries;
  }

  public void setResolutionEntries(List<ResolutionEntryDTO> resolutionEntries) {
    this.resolutionEntries = resolutionEntries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolutionStatementDTO resolutionStatementDTO = (ResolutionStatementDTO) o;
    return Objects.equals(this.height, resolutionStatementDTO.height) &&
        Objects.equals(this.unresolved, resolutionStatementDTO.unresolved) &&
        Objects.equals(this.resolutionEntries, resolutionStatementDTO.resolutionEntries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, unresolved, resolutionEntries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolutionStatementDTO {\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    unresolved: ").append(toIndentedString(unresolved)).append("\n");
    sb.append("    resolutionEntries: ").append(toIndentedString(resolutionEntries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

