/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResolutionEntryDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class ResolutionEntryDTO {

    public static final String SERIALIZED_NAME_SOURCE = "source";
    public static final String SERIALIZED_NAME_RESOLVED = "resolved";
    @SerializedName(SERIALIZED_NAME_SOURCE)
    private SourceDTO source = null;
    @SerializedName(SERIALIZED_NAME_RESOLVED)
    private List<Integer> resolved = new ArrayList<Integer>();

    public ResolutionEntryDTO source(SourceDTO source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     */
    @ApiModelProperty(required = true, value = "")
    public SourceDTO getSource() {
        return source;
    }

    public void setSource(SourceDTO source) {
        this.source = source;
    }

    public ResolutionEntryDTO resolved(List<Integer> resolved) {
        this.resolved = resolved;
        return this;
    }

    public ResolutionEntryDTO addResolvedItem(Integer resolvedItem) {
        this.resolved.add(resolvedItem);
        return this;
    }

    /**
     * Get resolved
     *
     * @return resolved
     */
    @ApiModelProperty(example = "[lower, higher]", required = true, value = "")
    public List<Integer> getResolved() {
        return resolved;
    }

    public void setResolved(List<Integer> resolved) {
        this.resolved = resolved;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResolutionEntryDTO resolutionEntryDTO = (ResolutionEntryDTO) o;
        return Objects.equals(this.source, resolutionEntryDTO.source)
            && Objects.equals(this.resolved, resolutionEntryDTO.resolved);
    }

    @Override
    public int hashCode() {
        return Objects.hash(source, resolved);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResolutionEntryDTO {\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    resolved: ").append(toIndentedString(resolved)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
