/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.nem.sdk.infrastructure.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ServerInfoDTO
 */
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2019-06-20T19:56:23.892+01:00[Europe/London]")
public class ServerInfoDTO {

    public static final String SERIALIZED_NAME_REST_VERSION = "restVersion";
    public static final String SERIALIZED_NAME_SDK_VERSION = "sdkVersion";
    @SerializedName(SERIALIZED_NAME_REST_VERSION)
    private String restVersion;
    @SerializedName(SERIALIZED_NAME_SDK_VERSION)
    private String sdkVersion;

    public ServerInfoDTO restVersion(String restVersion) {
        this.restVersion = restVersion;
        return this;
    }

    /**
     * The catapult-rest component version.
     *
     * @return restVersion
     */
    @ApiModelProperty(
        example = "1.0.14",
        required = true,
        value = "The catapult-rest component version.")
    public String getRestVersion() {
        return restVersion;
    }

    public void setRestVersion(String restVersion) {
        this.restVersion = restVersion;
    }

    public ServerInfoDTO sdkVersion(String sdkVersion) {
        this.sdkVersion = sdkVersion;
        return this;
    }

    /**
     * The catapult-sdk component version.
     *
     * @return sdkVersion
     */
    @ApiModelProperty(
        example = "0.7.14",
        required = true,
        value = "The catapult-sdk component version.")
    public String getSdkVersion() {
        return sdkVersion;
    }

    public void setSdkVersion(String sdkVersion) {
        this.sdkVersion = sdkVersion;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServerInfoDTO serverInfoDTO = (ServerInfoDTO) o;
        return Objects.equals(this.restVersion, serverInfoDTO.restVersion)
            && Objects.equals(this.sdkVersion, serverInfoDTO.sdkVersion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(restVersion, sdkVersion);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServerInfoDTO {\n");
        sb.append("    restVersion: ").append(toIndentedString(restVersion)).append("\n");
        sb.append("    sdkVersion: ").append(toIndentedString(sdkVersion)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
