/*
 * Copyright 2020 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest 1.0.20.20
 *
 * The version of the OpenAPI document: 0.8.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nem.symbol.sdk.model.network;

/**
 * MosaicRestrictionNetworkPropertiesDTO
 */
public class MosaicRestrictionNetworkProperties {

  /**
   * Maximum number of mosaic restriction values.
   **/
  private final String maxMosaicRestrictionValues;


  public MosaicRestrictionNetworkProperties(String maxMosaicRestrictionValues) {
    this.maxMosaicRestrictionValues = maxMosaicRestrictionValues;
  }

  public String getMaxMosaicRestrictionValues() {
    return maxMosaicRestrictionValues;
  }
}

