/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest 1.0.20.34
 *
 * The version of the OpenAPI document: 0.8.12
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.nem.symbol.sdk.api;

/**
 * The order by of a block search operation.
 */
public enum BlockOrderBy {

    ID("id"),

    HEIGHT("height");

    private final String value;

    BlockOrderBy(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}

